apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booksreview-ingress
  labels:
    name: booksreview-ingress
spec:
  rules:
    - host: ingress.destiaeka.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: booksreview-service
                port:
                  number: 80